name: "Verifications"

on:
  push:
  pull_request:

jobs:
  verifications:
    name: "Code verifications"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          cache: false
      - uses: actions-rust-lang/rustfmt@v1
        continue-on-error: true
      - run: cargo build --release
      - run: cargo clippy
      - run: tar -czf "i3-switch-tabs-${{ github.ref_name }}-linux-bin-x86_64.tar.gz" "target/release/i3-switch-tabs"
      - name: "Release"
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: "i3-switch-tabs-${{ github.ref_name }}-linux-bin-x86_64.tar.gz"
