name: "CI workflow"

on:
  push:
  pull_request:

jobs:
  ci_workflow:
    name: "CI workflow"
    runs-on: ubuntu-latest
    env:
      release_archive_name: "i3-switch-tabs-${{ github.ref_type == 'tag' && github.ref_name || github.sha }}-linux-bin-x86_64.tar.gz"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          cache: false
      - uses: actions-rust-lang/rustfmt@v1
        continue-on-error: true
      - run: cargo build --release
      - run: cargo clippy
      - run: tar -czf "${{ env.release_archive_name }}" "target/release/i3-switch-tabs"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.release_archive_name }}
          path: ${{ env.release_archive_name }}
          retention-days: 5
      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{ env.release_archive_name }}
